title: Likha RPA
description: Documentation for the Likha Windows-first RPA platform.
theme: jekyll-theme-cayman

plugins:
  - jekyll-optional-front-matter
  - jekyll-relative-links

optional_front_matter:
  remove_originals: true

relative_links:
  enabled: true
  collections: true

include:
  - README.md

