title: Likha RPA
description: Documentation for the Likha Windows-first RPA platform.
theme: jekyll-theme-cayman

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

include:
  - README.md

